version: "3.8"

services:
  tsrq:
    build:
        context: .
    volumes:
      - ./config.yaml:/usr/local/bin/config.yaml
    ports:
      - "9999:9999"

  redis:
    image: redis/redis-stack:latest
    command: ["redis-stack-server"]
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/var/lib/redis-stack

volumes:
  redis_data: